version: "3.3"
services:
  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_DB: "demo_project_book"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/data/:/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "1337:5432"